apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-service
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: demo
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-credentials
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-jwt-secret
                  key: secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
  selector:
    app: {{ .Release.Name }}-service
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
type: Opaque
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-secret
type: Opaque
stringData:
  secret: {{ .Values.secrets.jwtSecret | quote }}
