apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: demo
type: Opaque
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: demo
type: Opaque
stringData:
  password: redispass
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: demo
type: Opaque
stringData:
  secret: "mySecretKey123456789012345678901234567890"
